### ISSUE TITLE
ROS melodic release?

### ISSUE THREAD

**Issue by v4hn** [eric-wieser/ros_numpy#16]
Hi again, it seems you did not release this package into ROS melodic yet.
Did you just not get around to do it yet or is there a specific reason?
It would be nice to see it available there!

**Comment by eric-wieser** [comment]
It's been a long time since I did a ROS release. I'm not even sure I have a ROS installation around at the moment, which makes it tricky to run `bloom-release`.

**Comment by jccurtis** [comment]
@eric-wieser if that is the case, can another user obtain maintainer access so this can be a simple `apt install`? These tools work nicely in `melodic` and will likely work fine in `noetic` next year provided there are no modifications for `python3`. Thanks for awesome work!

**Comment by eric-wieser** [comment]
I would be open to doing that, but am not immediately sure how to - granting maintenance access on this repo will not help.

**Comment by gstavrinos** [comment]
I would also like to see this package in Melodic/Noetic. I am also willing to help release and/or migrate it to Python 3.

**Comment by eric-wieser** [comment]
@gstavrinos: If you could work out exactly what permissions you need in order to release for me, please let me know. It should be possible to use the package today in newer ros releases simply by doing a git checkout.

**Comment by gstavrinos** [comment]
@eric-wieser Sure, I will try to look into it in the weekend.

**Comment by gstavrinos** [comment]
So, after a quick look, I think I definitely need access to the ros_numpy-release repo, but also to this one, in order to do some version bumps if required by bloom.

I am also eager to help migrate the package to Python3 (thus, ROS Noetic) if any changes are needed and generally offer maintainer support.

**Comment by eric-wieser** [comment]
I've added you to https://github.com/eric-wieser/ros_numpy-release @gstavrinos.

Are you able to do version-bumps via pull-requests alone, or does that not work well with bloom?

**Comment by gstavrinos** [comment]
Hey Eric, thanks. I think it will be easier and more efficient if I have access to this repo, too. If you feel uneasy about it, I will look into the PR method you proposed.

**Comment by eric-wieser** [comment]
@gstavrinos: Added you as a collaborator

**Comment by gstavrinos** [comment]
Thank you, Eric. I will get into it asap!

**Comment by marc-hanheide** [comment]
@gstavrinos , did you make any progress regarding the `melodic` release? We'd also need it urgently, and if you don't have the resources at the moment, I can also release into another repository under https://github.com/lcas-releases if @eric-wieser doesn't want to host future releases in his repository.

**Comment by gstavrinos** [comment]
@marc-hanheide, to be honest, it slipped my mind. I will do my best to release it in the next couple of days.

**Comment by gstavrinos** [comment]
@marc-hanheide, I just made the release. We are now waiting for the PR to be accepted and the next melodic sync! Once everything goes as expected, I will close this issue.

**Comment by marc-hanheide** [comment]
Thanks!!

**Comment by gstavrinos** [comment]
![](https://vignette.wikia.nocookie.net/en.futurama/images/a/ad/GoodNewsEveryone.jpg)

https://github.com/ros/rosdistro/pull/23892

**Comment by jccurtis** [comment]
Thanks @gstavrinos for following up on this!

**Comment by charlesyz** [comment]
Are there plans for a Noetic release? There don't seem to be any required changes for Python3. I've used the source project as-is in noetic.
