### ISSUE TITLE
Release for ROS noetic

### ISSUE THREAD

**Issue by mantkiew** [eric-wieser/ros_numpy#19]
Hello, could you please make a release for ROS Noetic (and Ubuntu 20.04)?

**Comment by charlesyz** [comment]
The package seems to be Python3 compatible as I've used the package in Python3.8 ROS Noetic without any modifications.

The only required action would be to create the package release

**Comment by gstavrinos** [comment]
I'll get to it asap.

**Comment by gstavrinos** [comment]
Released ros_numpy (https://github.com/ros/rosdistro/pull/26793). Closing this issue.
