### ISSUE TITLE
ros_numpy depends on `numpy < 1.24`

### ISSUE THREAD

**Issue by Kimame04** [eric-wieser/ros_numpy#35]
With [numpy 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html) removing `np.float` alias the following occurs when running the latest numpy version with `ros_numpy`

```
AttributeError: module 'numpy' has no attribute 'float'
```

For the moment, I'm guessing a rollback to 1.23 is required.

**Comment by Kimame04** [comment]
Never mind, this is a duplicate question of #32

**Comment by aravi-2001** [comment]
unsure how to interpret the fix, how is it solved? i'm facing this issue too
