### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by chandanlal92** [eric-wieser/ros_numpy#8]
Hi,
I wanted to convery numpy array to point cloud.I am facing follwing issue.
I get this error while using this library. Is there any workaround for this?
    
from .registry import converts_from_numpy, converts_to_numpy

ValueError: Attempted relative import in non-package

**Comment by eric-wieser** [comment]
In what file is that line of code? It sounds like your python path is not set up correctly

**Comment by eric-wieser** [comment]
Closing, this is an installation issue
